#!/bin/bash

aide() {
  echo 'SYNTAXE'
  echo 'Numerotation <DOSSIER CIBLE> [<NUM DE DEPART> <CRITERE> <PREFIXE> <SUFFIXE>]'
  echo 'Les éléments entre crochets sont optionnels'
  echo "Exemple de critère : '*.jpg' - Numérote les fichiers avec l'extension .jpg"
}

if [[ $# -lt 1 ]] || [[ $# -gt 5 ]]; then
  echo 'Nombre d’arguments invalide'
  aide
  exit 1
fi

if [[ ! -d "$1" ]]; then
  echo "Dossier invalide : $1"
  exit 1
fi

if [[ ! "$2" =~ ^[+-]?[0-9]+$ ]] && [[ $# -ge 2 ]]; then
  echo 'Numéro de départ invalide'
  aide
  exit 1
fi

if [[ $# -ge 2 ]]; then
  count=$(($2))
else
  count=0
fi

if [[ $# -ge 3 ]]; then
  criteria=$3
else
  criteria='*'
fi

if [[ $# -ge 4 ]]; then
  prefix=$4
else
  prefix=''
fi

if [[ $# -ge 5 ]]; then
  suffix=$5
else
  suffix=''
fi

echo "RENOMMAGE DES FICHIERS DANS $1"

read -p 'Prévisualiser les changements ? [RECOMMANDÉ] (O/n) ' preview
preview=$(echo "$preview" | tr '[:lower:]' '[:upper:]')

if [[ "$preview" == 'O' ]] || [[ -z "$preview" ]]; then
  for file in ${1}/$criteria; do
    echo "${file##*/} -> ${prefix}${count}${suffix}"
    count=$((count+1))
  done
fi

read -p 'Continuer ? (O/n) ' confirmation
confirmation=$(echo "$confirmation" | tr '[:lower:]' '[:upper:]')

if [[ "$confirmation" == 'O' ]] || [[ -z "$confirmation" ]]; then
  for file in ${1}/$criteria; do
    mv "$file" "${prefix}${count}${suffix}"
    count=$((count+1))
  done
  echo 'Terminé !'
fi
